parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $appName: '%vdm_library.app_name%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Vdm\Bundle\LibraryBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,vendor,Kernel.php}'

    Vdm\Bundle\LibraryBundle\Transport\Manual\VdmManualExecutorCollection:
        # inject all services tagged with vdm.manual_executor as first argument
        arguments: [!tagged_locator { tag: 'vdm.manual_executor',  index_by: 'key', default_index_method: 'getCode' }]