language: php
php:
  - 7.3
  - 7.4
before_install:
  - sudo apt-get -y install librabbitmq-dev
before_script:
  - echo '' | pecl install amqp
  - composer install -n
script:
  - ./vendor/bin/phpunit Tests/
