language: php
services:
  - mongodb
php:
  - 7.3
  - 7.4
before_install:
  - sudo apt-get -y install librabbitmq-dev
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - echo '' | pecl install amqp mongodb
  - composer install -n
script:
  - ./vendor/bin/phpunit Tests/
