{
 "title": "VDM dataflow",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "query": {
     "query": "label_values(vdm_running, appName)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Compteurs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total consommé",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vdm_consumed{appName=\"$app\"}"
    }
   ]
  },
  {
   "title": "Total consommé (période)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdm_consumed{appName=\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate consommé",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "avg(irate(vdm_consumed{appName=\"$app\"}[$__interval])) by (appName)"
    }
   ]
  },
  {
   "title": "Total traité",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vdm_handled{appName=\"$app\"}"
    }
   ]
  },
  {
   "title": "Total traité (période)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdm_handled{appName=\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate traité",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "avg(irate(vdm_handled{appName=\"$app\"}[$__interval])) by (appName)"
    }
   ]
  },
  {
   "title": "Total produit",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vdm_produced{appName=\"$app\"}"
    }
   ]
  },
  {
   "title": "Total produit (période)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vdm_produced{appName=\"$app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate produit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "avg(irate(vdm_produced{appName=\"$app\"}[$__interval])) by (appName)"
    }
   ]
  },
  {
   "title": "Gauges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average memory",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(vdm_memory{appName=\"$app\"})"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(vdm_memory{appName=\"$app\"}) by (route)"
      }
     ]
    },
    {
     "title": "Average duration",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(vdm_duration{appName=\"$app\"})"
      }
     ]
    },
    {
     "title": "Duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(vdm_duration{appName=\"$app\"}) by (route)"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx Percents",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(vdm_http_status_code{appName=\"$app\", statusCode=~\"2.+\"}[$__range])) * 100 / sum(rate(vdm_http_status_code{appName=\"$app\"}[$__range]))"
      }
     ]
    },
    {
     "title": "3xx Percents",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(vdm_http_status_code{appName=\"$app\", statusCode=~\"3.+\"}[$__range])) * 100 / sum(rate(vdm_http_status_code{appName=\"$app\"}[$__range]))"
      }
     ]
    },
    {
     "title": "4xx Percents",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(vdm_http_status_code{appName=\"$app\", statusCode=~\"4.+\"}[$__range])) * 100 / sum(rate(vdm_http_status_code{appName=\"$app\"}[$__range]))"
      }
     ]
    },
    {
     "title": "5xx Percents",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(vdm_http_status_code{appName=\"$app\", statusCode=~\"5.+\"}[$__range])) * 100 / sum(rate(vdm_http_status_code{appName=\"$app\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(vdm_http_status_code{appName=\"$app\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Rate total (per seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vdm_http_status_code{appName=\"$app\"}[$__interval])) by (appName)"
      }
     ]
    },
    {
     "title": "Rate per http code (per seconds)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(irate(vdm_http_status_code{appName=\"$app\"}[$__interval])) by (appName, statusCode)"
      }
     ]
    },
    {
     "title": "Average response time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(vdm_http_response_time{appName=\"$app\"})"
      }
     ]
    },
    {
     "title": "Response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 19, "x": 5, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(vdm_http_response_time{appName=\"$app\"}) by (appName)"
      }
     ]
    }
   ]
  }
 ]
}